#!/bin/sh
# https://github.com/chronos-tachyon/dotfiles
set -e -u
trap '[ $? -eq 0 ] || echo FAIL >&2' EXIT

if [ $# -ne 0 ]; then
  sed -e 's/^  //' >&2 <<__EOF
  Outputs an executable script named 'install-dotfiles' in the current directory.
  Usage: $0

  This script is useful if you don't want ~/.dotfiles to be a Git client.

  ERROR: Unexpected argument: $1
__EOF
  exit 1
fi

src="$(cd "$(dirname "$0")" && pwd)"

echo 'Creating: install-dotfiles'
exec 3>install-dotfiles
cat >&3 <<'EOF'
#!/bin/sh
# https://github.com/chronos-tachyon/dotfiles
set -e -u
trap '[ $? -eq 0 ] || echo FAIL >&2' EXIT

if [ $# -eq 0 ]; then
  dest="${HOME}/.dotfiles"
elif [ "${1#-}" = "$1" ]; then
  dest="$1"
else
  sed -e 's/^  //' >&2 <<__EOF
  Installs a bundle of stock dotfiles to ~/.dotfiles.
  Usage: $0 [<install-dir>]
    <install-dir> defaults to ~/.dotfiles

  ERROR: Unknown flag: $1
__EOF
  exit 1
fi

echo "Installing to: ${dest}"
mkdir -p "$dest"
cd "$dest"
rm -rf base
uudecode -o /dev/stdout <<'EOA' | tar -xzf -
EOF
tar -czf - -C "$src" apply base override patch | uuencode -m base.tar.gz >&3
cat >&3 <<'EOF'
EOA
chmod -R go= base/.bash/history.d base/.vim/swap
EOF
exec 3>&-

chmod +x install-dotfiles
